fix: disable cosign verify blob due to error
```
could not find entry in tlog: searching log query: [POST /api/v1/log/entries/retrieve][404] searchLogQuery default  &{Code:404 Message:rpc error: code = NotFound desc = No leaf found for hash: a2020d8a47f7aaa28ae0d36be7881650f74c1831d022f4a6c2908e45c8eea15a in tree size 36475}Error: verifying blob [https://github.com/goreleaser/goreleaser/releases/download/v1.11.4/checksums.txt]: searching log query: [POST /api/v1/log/entries/retrieve][404] searchLogQuery default  &{Code:404 Message:rpc error: code = NotFound desc = No leaf found for hash: a2020d8a47f7aaa28ae0d36be7881650f74c1831d022f4a6c2908e45c8eea15a in tree size 36475}
main.go:62: error during command execution: verifying blob [https://github.com/goreleaser/goreleaser/releases/download/v1.11.4/checksums.txt]: searching log query: [POST /api/v1/log/entries/retrieve][404] searchLogQuery default  &{Code:404 Message:rpc error: code = NotFound desc = No leaf found for hash: a2020d8a47f7aaa28ae0d36be7881650f74c1831d022f4a6c2908e45c8eea15a in tree size 36475}
```

Signed-off-by: gythialy <gythialy.koo+github@gmail.com>